package com.af.pb.domain.layer

import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName

data class AdConfig(
    @SerializedName("use_inter_splash") @Expose var useInterSplash: Boolean = true,
    @SerializedName("banner_splash") @Expose var enableBannerSplash: Boolean = true,
    @SerializedName("banner_splash_2f") @Expose var enableBannerSplash2f: Boolean = true,
    @SerializedName("inter_splash") @Expose var enableInterSplash: Boolean = true,
    @SerializedName("inter_splash_2f") @Expose var enableInterSplash2f: Boolean = true,
    @SerializedName("native_full_splash") @Expose var enableNativeFullSplash: Boolean = true,
    @SerializedName("native_full_splash_2f") @Expose var enableNativeFullSplash2f: Boolean = true,
    @SerializedName("aoa_splash") @Expose var enableAppOpenSplash: Boolean = true,
    @SerializedName("app_open_resume") @Expose var enableAppOpenResume: Boolean = true,
    @SerializedName("native_language") @Expose var enableNativeLanguage: Boolean = true,
    @SerializedName("native_language_2f") @Expose var enableNativeLanguage2f: Boolean = true,
    @SerializedName("native_language_select") @Expose var enableNativeLanguageSelect: Boolean = true,
    @SerializedName("native_language_select_2f") @Expose var enableNativeLanguageSelect2f: Boolean = true,
    @SerializedName("native_obd1") @Expose var enableNativeObd1: Boolean = true,
    @SerializedName("native_obd1_2f") @Expose var enableNativeObd12f: Boolean = true,
    @SerializedName("native_ob12_full") @Expose var enableNativeOb12Full: Boolean = true,
    @SerializedName("native_obd2") @Expose var enableNativeObd2: Boolean = true,
    @SerializedName("native_obd2_2f") @Expose var enableNativeObd22f: Boolean = true,
    @SerializedName("native_obd3") @Expose var enableNativeObd3: Boolean = true,
    @SerializedName("native_obd3_2f") @Expose var enableNativeObd32f: Boolean = true,
    @SerializedName("native_ob23_full") @Expose var enableNativeOb23Full: Boolean = true,
    @SerializedName("native_ob23_full_2f") @Expose var enableNativeOb23Full2f: Boolean = true,
    @SerializedName("native_ob34_full") @Expose var enableNativeOb34Full: Boolean = true,
    @SerializedName("native_obd4") @Expose var enableNativeObd4: Boolean = true,
    @SerializedName("inter_function") @Expose var enableInterFunction: Boolean = true,
    @SerializedName("inter_back") @Expose var enableInterBack: Boolean = true,
    @SerializedName("banner_all") @Expose var enableBannerAll: Boolean = true,
    @SerializedName("reward_film") @Expose var enableRewardFilm: Boolean = true,
    @SerializedName("reward_top_film") @Expose var enableRewardTopFilm: Boolean = true,
    @SerializedName("native_full_play_film") @Expose var enableNativeFullPlayFilm: Boolean = true,
    @SerializedName("native_full_for_you") @Expose var enableNativeFullForYou: Boolean = true,
    @SerializedName("inter_cancel_paywall") @Expose var enableInterCancelPaywall: Boolean = true,
    @SerializedName("native_uninstall") @Expose var enableNativeUninstall: Boolean = true,
    @SerializedName("banner_collap") @Expose var enableBannerCollapse: Boolean = true,
    @SerializedName("inter_home") @Expose var enableInterHome: Boolean = true,
    @SerializedName("reward_quality") @Expose var enableRewardQuality: Boolean = true,
    @SerializedName("native_full_remove") @Expose var enableNativeFullRemove: Boolean = true,
    @SerializedName("native_setting") @Expose var enableNativeSetting: Boolean = true,
    @SerializedName("native_exit") @Expose var enableNativeExit: Boolean = true,
    @SerializedName("inter_exit") @Expose var enableInterExit: Boolean = true,
    @SerializedName("cta_language_top") @Expose var ctaLanguageTop: Boolean = false,
    @SerializedName("cta_onboarding_top") @Expose var ctaOnBoardingTop: Boolean = false,
    @SerializedName("time_show_close_ob_full") @Expose var timeShowCloseObFull: Int = 3,
    @SerializedName("time_auto_close_native_full") @Expose var timeAutoCloseNativeFull: Int = 3,
    @SerializedName("inter_show_frequency") @Expose var interShowFrequency: Int = 2,
    @SerializedName("interval_inter") @Expose var interval: Int = 30
)
